### PR TITLE
Use `rustls-tls` instead of `OpenSSL`

### LINKED ISSUE #61: Run `Build (x86_64-unknown-linux-gnu)` job
This job is waiting to run for over 40 minutes now. This causes all GitHub workflows using [setup-aftman](https://github.com/ok-nick/setup-aftman) action to fail as it uses the latest tag by default.

### PR DESCRIPTION
**Pull request by DervexDev**
Closes #61

### CODE REVIEW

**Comment by LPGhatguy** [comment]
Huh. I wonder why the 1.58 test suite has started failing, I noticed that on main too.

**Comment by LPGhatguy** [comment]
I bumped the MSRV on the main branch to 1.60.0. If you rebase or pull main, it'll rerun the test suite and we'll see.

**Comment by DervexDev** [comment]
Done!

**Comment by DervexDev** [comment]
Oh it failed again, looks like reqwest `v0.11.27` requires rustc `1.63.0`

**Comment by LPGhatguy** [comment]
Feel free to bump the MSRV in the workflow file until it does work 😅

**Comment by DervexDev** [comment]
[Succeeded](https://github.com/DervexDev/aftman/actions/runs/8936752120/job/24547702068) with `1.65.0`

**Comment by LPGhatguy** [comment]
It looks like `openssl` is still ending up in the tree if you search in `Cargo.lock`. I think we need to set `default-features = false` as well in order to not use native TLS (and thus OpenSSL) on Linux.

You can compare this PR to jackTabsCode/asphalt#37 to see the difference.

**Comment by DervexDev** [comment]
It is actually not necessary to make Linux builds succeed but that's definitely better as we have less dependencies.

**Comment by LPGhatguy** [comment]
Right, not necessary to make the builds succeed, but it is necessary to ensure the binaries can run on machines that don't have a compatible version of OpenSSL installed. Otherwise, users would download and run the binary on those machines and find that they fail with a load-time error.

**Review by LPGhatguy — APPROVED** [review]
LGTM! Merging when CI finishes.

**Pull request merged**
