### PR TITLE
Support self-install on Unix

### LINKED ISSUE #10: Supporting adding to PATH on non-Windows platforms
We can follow what Cargo does here.

They append to `~/.zshenv` and/or `~/.profile` the following:

```bash
. "$HOME/.cargo/env"
```

and then include this script, `~/.cargo/env`:

```bash
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$HOME/.cargo/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac
```

This seems reasonable to me.

### PR DESCRIPTION
**Pull request by Yumacide**
Closes #10.

### CODE REVIEW

**Comment by Yumacide** [comment]
Closes #10!

**Comment by LPGhatguy** [comment]
I updated your description, but you need to put closing keywords in the main description in order for GitHub to pick them up. You can edit your PR at any time!

**Comment by LPGhatguy** [comment]
This PR appears to be taken verbatim from the Rustup source code. In the future, when contributing PRs to any project, you should include attribution for code that you did not write both in your PR body and in the source code, following the original code's license.

The upstream project, Rustup, is dual-licensed under the MIT and Apache-2.0 licenses. While it is possible to attribute this code to them and include an exception that some code in Aftman is owned by the authors of Rustup, I would rather keep this entire project under the same license.

**Comment by Yumacide** [comment]
Rustup's README says: "Licensed under either of Apache 2.0 or MIT at your option." so you can keep the MIT license, but I should indeed have added some attribution. Thanks!

**Comment by LPGhatguy** [comment]
Keeping the MIT license is one thing, but I would like to keep all of the code under this project under the same copyright notice without additional attribution or asterisks. Instead of taking this code wholesale from Rustup, I would rather we write a simpler solution that fits in with the codebase and stays owned solely by Aftman contributors.

**Comment by LPGhatguy** [comment]
Replaced by #16.

**Pull request closed without merging**
