### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by Yumacide**

### CODE REVIEW

**Comment by Yumacide** [comment]
Seems like clippy's in the CI but you didn't pass `-D warnings`. Is this intentional?

**Comment by LPGhatguy** [comment]
> Seems like clippy's in the CI but you didn't pass `-D warnings`. Is this intentional?

There _are_ some things that clippy will deny by default. I think that using `-D warnings` is usually a mistake because it can cause new PRs to fail CI even though it isn't their fault, from a new clippy version.

**Review by LPGhatguy — APPROVED** [review]

**Comment by Yumacide** [comment]
Whoops.

**Comment by LPGhatguy** [comment]
Oh, deleting branches once they're merged is totally fine. GitHub recommends this usually and has settings to do it for you.

**Pull request merged**
